<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Issue Certificate | SmartIntern</title>

<!-- Bootstrap 5 -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<style>
    body {
        background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
        min-height: 100vh;
    }

    .card {
        border-radius: 15px;
    }

    .form-label {
        font-weight: 500;
    }
</style>

</head>
<body>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg p-4">
                
                <h4 class="text-center mb-4">Issue Certificate</h4>

                <form action="saveCertificate" method="post">

                    <!-- Enrollment ID (FK) -->
                    <div class="mb-3">
                        <label class="form-label">Enrollment ID</label>
                        <input type="number" 
                               name="enrollmentId" 
                               class="form-control"
                               placeholder="Enter Enrollment ID"
                               required>
                    </div>

                    <!-- Certificate URL -->
                    <div class="mb-3">
                        <label class="form-label">Certificate URL</label>
                        <input type="text" 
                               name="certificateURL" 
                               class="form-control"
                               placeholder="https://example.com/certificate.pdf"
                               required>
                    </div>

                    <!-- Issued Date -->
                    <div class="mb-3">
                        <label class="form-label">Issued Date</label>
                        <input type="date" 
                               name="issuedDate" 
                               class="form-control"
                               required>
                    </div>

                    <!-- Verification Code Info -->
                    <div class="mb-3">
                        <label class="form-label">Verification Code</label>
                        <input type="text" 
                               class="form-control"
                               value="Auto Generated by System"
                               disabled>
                        <small class="text-muted">
                            Unique verification code will be generated automatically.
                        </small>
                    </div>

                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">
                            Save Certificate
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

</body>
</html>
